# This is a basic workflow to help you get started with Actions

name: Install on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: home-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get to work dir
        run: cd $GITHUB_WORKSPACE

      - name: Get to target dir
        run: cargo install --path .

      - name: Generate node package using wasm-pack
        run: wasm-pack build -t nodejs --features wasm

      - name: Update node package
        run: rsync -avz --delete pkg/ ~/notification-system-wasm/pkg/
